name: Create PR Environment

on:
  issue_comment:
    types: created

permissions:
  id-token: write
  contents: read

jobs:
  pr_comment:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/build')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: thomasv314/gha-composite-test
        path: ./github/actions/gha-composite-test
        branch: main
        token: ${{ secrets.GHA_TOKEN }}

    - name: Parse Comments
      id: parse-comments
      uses: ./github/actions/gha-composite-test/parse-comments
      with:
        github-token: ${{ secrets.GHA_TOKEN }}
        #        github-comment-prefix: '/build'
