name: Create PR Environment

on:
  issue_comment:
    types: created

permissions:
  id-token: write
  contents: read

jobs:
  pr_comment:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/build')
    steps:

    - name: Parse Comments
      id: parse-comments
      uses: thomasv314/gha-composite-test/parse-comments
      with:
        github-token: ${{ github.token }}
        #        github-comment-prefix: '/build'
