name: Create PR Environment

on:
  issue_comment:
    types: created

permissions:
  id-token: write
  contents: read

jobs:
  pr_comment:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/build')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: thomasv314/gha-composite
        path: ./github/gha-composite/
        branch: main
        token: ${{ secrets.GHA_TOKEN }}

    - uses: ./github/gha-composite/actions/parse-arguments
      with:
        github-token: ${{ secrets.GHA_TOKEN }}
        command-prefix: "/build"
        #        github-comment-prefix: '/build'
